# Generated by Django 4.2.1 on 2023-06-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollment',
            new_name='Courses_Name',
        ),
    ]
