# Generated by Django 4.2.1 on 2023-06-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0002_rename_enrollment_courses_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='images/')),
                ('desrciption', models.TextField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='images/')),
                ('highlights', models.TextField(null=True)),
                ('KeyFutures', models.TextField(null=True)),
            ],
        ),
    ]
