# Generated by Django 4.2.1 on 2023-06-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0003_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoattended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile_Number', models.CharField(max_length=20)),
                ('Courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vcube.courses_name')),
                ('Training', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vcube.training')),
            ],
        ),
    ]
