# Generated by Django 4.2.1 on 2023-06-14 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0012_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colabrations',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='courses_name',
            name='crsname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demos',
            name='Training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vcube.training'),
        ),
        migrations.AlterField(
            model_name='review',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
