# Generated by Django 4.2.1 on 2023-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0020_student_actual_fees_student_admission_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='actual_fees',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fees_paid',
        ),
        migrations.AddField(
            model_name='demoattended',
            name='status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3),
        ),
    ]
