# Generated by Django 4.2.1 on 2023-07-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0021_remove_student_actual_fees_remove_student_fees_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demoattended',
            old_name='status',
            new_name='Join',
        ),
    ]
