# Generated by Django 4.2.1 on 2023-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0022_rename_status_demoattended_join'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Mobile_Number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='newstudent',
            name='Mobile_Number',
            field=models.CharField(max_length=12),
        ),
    ]
