# Generated by Django 4.2.1 on 2023-08-04 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0025_test_interview_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='placed_students/')),
            ],
        ),
    ]
