# Generated by Django 4.2.1 on 2023-08-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0026_placedstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacedStudent',
        ),
    ]
