# Generated by Django 4.2.1 on 2023-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0028_gender_newstudent_graduation_newstudent_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newstudent',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
