# Generated by Django 4.2.1 on 2023-08-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0029_alter_newstudent_gender_delete_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newstudent',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='newstudent',
            name='Graduation',
        ),
    ]
