# Generated by Django 4.2.1 on 2023-08-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0030_remove_newstudent_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newstudent',
            name='Graduation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
