# Generated by Django 4.2.1 on 2023-08-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcube', '0031_newstudent_graduation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('experience', models.CharField(max_length=20)),
                ('experience_details', models.CharField(blank=True, max_length=255, null=True)),
                ('education', models.CharField(max_length=50)),
                ('other_qualification', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(max_length=50)),
                ('sub_course', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('ampm', models.CharField(max_length=2)),
            ],
        ),
    ]
